### ISSUE TITLE
[Bug] 一些translate

### ISSUE THREAD

**Issue by shenjackyuanjie** [The-Cat-Town-Craft/Carpet-TCTC-Addition#13]
### Minecraft Version

1165

### Carpet TCTC Addition Version

2.0.185

### Description

![image](https://user-images.githubusercontent.com/54507071/211204572-5bd300b4-4d7c-4c10-8797-c3ba4077fbc3.png)

### To Reproduce

![image](https://user-images.githubusercontent.com/54507071/211204595-3aa3291a-82fd-4683-863c-9fc0dfd02552.png)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
尝试这个版本[2.0.186+6be1dbd](https://github.com/The-Cat-Town-Craft/Carpet-TCTC-Addition/releases/tag/dev-186)。

**Comment by shenjackyuanjie** [comment]
看到啦~
