### ISSUE TITLE
1.19 support please:)

### ISSUE THREAD

**Issue by ghost** [The-Cat-Town-Craft/Carpet-TCTC-Addition#5]

**Comment by Hendrix-Shen** [comment]
Not yet fully tested, but it supports 1.19. [2.0.154+970c137](https://github.com/The-Cat-Town-Craft/Carpet-TCTC-Addition/suites/7093608261/artifacts/280600568)

**Comment by ghost** [comment]
Hello, thank you!
Error on client loading:
https://pastebin.com/raw/yyX0qv0v
https://pastebin.com/raw/7q0fyy7G

I hope it helps.

**Comment by Hendrix-Shen** [comment]
Try this version: [2.0.157+7103cc5](https://github.com/The-Cat-Town-Craft/Carpet-TCTC-Addition/suites/7095881380/artifacts/280785093)

**Comment by ghost** [comment]
I got another error: https://pastebin.com/raw/4SUxXG9r

**Comment by Hendrix-Shen** [comment]
The problem occurred when a target was redirected in conjunction with Carpet Fixes. This is a redirect conflict. I had to find an amalgamated way to deal with this problem.
