### ISSUE TITLE
1.19.2 support please 🥰

### ISSUE THREAD

**Issue by ghost** [The-Cat-Town-Craft/Carpet-TCTC-Addition#9]
### What new features do you want?

![image](https://user-images.githubusercontent.com/75373609/184268793-7a7faa78-d84a-4f31-b7e9-64fb019037d9.png)

### Latest CI build tested

- [X] I confirm that the feature I requested is not in the latest CI build.

**Comment by tianxiu2b2t** [comment]
support 1.19.2 please, I need this mod. If mod not support 1.19.2 I so unhappy :)

**Comment by ghost** [comment]
I think we can expect soon a release, since Hendrix-Shen-kun was working hard on TweakMyClient and released now the first Stable version😋

**Comment by Hendrix-Shen** [comment]
I have uploaded a temporary solution for Minecraft 1.19.2. Please use this version [2.0.178+9fafcac](https://github.com/The-Cat-Town-Craft/Carpet-TCTC-Addition/suites/7906668611/artifacts/336500056). Do not close the issue, the problem is not fully resolved, although at the moment it looks like he works. Better solutions and more testing still needed. The original plan was to wait for the carpet core to fully migrate, but the current stacked state is just awful.

**Comment by ghost** [comment]
Yay, thanks ❤️
If I encounter any problem I will share it.

**Comment by Hendrix-Shen** [comment]
This project is now almost complete with migration tasks. You can try this version [2.0.182+c98605f](https://github.com/The-Cat-Town-Craft/Carpet-TCTC-Addition/releases/tag/dev-182). This version uses the preview version of MagicLib and requires version >= [0.6.179+c78b523](https://github.com/Hendrix-Shen/MagicLib/releases/tag/dev%2F0.6.179). I think the system currently works.

**Comment by ghost** [comment]
Hello @Hendrix-Shen, with the newest versions of TCTC and MagicLib, I'm getting this error here:
https://pastebin.com/raw/SyM6B8FG

**Comment by Hendrix-Shen** [comment]
Oh, our magic broke the CarpetRuleRegistrar of CarpetTisAddition. I am trying to fix this problem.

**Comment by Hendrix-Shen** [comment]
Try MagicLib [0.6.180+a74092a](https://github.com/Hendrix-Shen/MagicLib/releases/tag/dev%2F0.6.180) and the problem should be solved.

**Comment by ghost** [comment]
Everything works, thanks for your fast update pushing.
Using the mod for 2 weeks now and every regular update from it - everything works good.

**Comment by ghost** [comment]
Ohhh, it's long been done - this can be closed 😊
